[project]
name = "celery-fastapi-dockerized"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.3.0",
    "redis>=7.0.1",
]
